stages:
  - copy_latest_jars


before_script:
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_BUILD_REF_NAME

after_script:
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_BUILD_REF_NAME

copy_svarog:
  stage: copy_latest_jars
  script:
    - git remote set-url origin git@gitlab.prtech.mk:prtech/common_libs.git
    - git fetch origin $CI_BUILD_REF_NAME
    - git reset --hard origin/$CI_BUILD_REF_NAME
    - git checkout $CI_BUILD_REF_NAME
    - git pull
    - |
      if [ -n "${JAR_TO_COPY}" ]; then
        echo "new jar found `${JAR_TO_COPY}`"
        cp /home/gitlab-runner/JARS/"${JAR_TO_COPY}" .
        git add "${JAR_TO_COPY}"
        git commit -m "Push latest jar `${JAR_TO_COPY}`" || exit 0
        git push origin HEAD:$CI_BUILD_REF_NAME
      fi
  only:
    - master
