stages:
  - copy_latest_jars


before_script:
  - git reset --hard HEAD
  - git clean -fd
  - git pull origin $CI_COMMIT_REF_NAME

after_script:
  - git reset --hard HEAD
  - git clean -fd
  - git pull origin $CI_COMMIT_REF_NAME

copy_jars:
  stage: copy_latest_jars
  script:
    - git remote set-url origin git@gitlab.prtech.mk:prtech/common_libs.git
    - git fetch origin $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - git clean -df
    - git pull
    - |
      if [ -n "${JAR_TO_COPY}" ]; then
        echo "new jar found $JAR_TO_COPY"
        if [[ ${JAR_TO_COPY} =~ "svarog-2.1."+[0-9]+"-"+[0-9]+".jar" ]] || [[ ${JAR_TO_COPY} =~ "svarog-2."+[0-9]+"_dev" ]];
          then
            git rm svarog-2.* || true
            cp /home/gitlab-runner/JARS/$CI_COMMIT_REF_NAME/$JAR_TO_COPY .
            git add $JAR_TO_COPY
            git commit -m "Push latest SVAROG $JAR_TO_COPY for branch $CI_COMMIT_REF_NAME [ci_skip]" || exit 0
            git push origin HEAD:$CI_COMMIT_REF_NAME
            echo "Trigger new builds dependant on ${JAR_TO_COPY}"
            # stribog
            echo "Trigger stribog (batch executor)"
            curl -X POST -F token=8e1f5720d7707a28f6252963891f01 -F ref=$CI_COMMIT_REF_NAME https://gitlab.prtech.mk/api/v4/projects/5/trigger/pipeline
            # svarog_reports
            echo "Trigger svarog_reports"
            curl -X POST -F token=eec8a37fd0abf5d5988e26fd737811 -F ref=$CI_COMMIT_REF_NAME https://gitlab.prtech.mk/api/v4/projects/34/trigger/pipeline
            # afpzrr_sop_triglav_plugin
            # echo "Trigger afpzrr_sop_triglav_plugin"
            # curl -X POST -F token=bb635b9b8f32207cff88191d5dd368 -F ref=$CI_COMMIT_REF_NAME https://gitlab.prtech.mk/api/v4/projects/21/trigger/pipeline
            # afsard_triglav_plugin
            echo "Trigger afsard_triglav_plugin"
            curl -X POST -F token=d6e50ed4711d45e77545eddc7f9835 -F ref=$CI_COMMIT_REF_NAME https://gitlab.prtech.mk/api/v4/projects/36/trigger/pipeline
          else
            cp /home/gitlab-runner/JARS/$CI_COMMIT_REF_NAME/$JAR_TO_COPY .
            git add $JAR_TO_COPY
            git commit -m "Push latest jar $JAR_TO_COPY for branch $CI_COMMIT_REF_NAME [ci_skip]" || exit 0
            git push origin HEAD:$CI_COMMIT_REF_NAME
            echo "Trigger triglav_rest build";
            curl -X POST -F token=9176d5285570b34e7fd409ef5c51c4 -F ref=$CI_COMMIT_REF_NAME https://gitlab.prtech.mk/api/v4/projects/17/trigger/pipeline;
        fi
      fi
  only:
    - master
    - staging
    - dev
    - triggers
